### ISSUE TITLE
带我一个玩呗？

### ISSUE THREAD

**Issue by zhaozhe0831** [Smallpath/Blog#1]
我想弄个 VuePress，在谷歌上搜 spa 博客系统 ，就搜到你了，情投意合，一见钟情，看好你哦。
我能干点啥，也想出份力~

**Comment by Smallpath** [comment]
谢谢关注， 这两天我在弄ssr， 比较麻烦但估计周五前能弄好， 你要部署的话可以下载之前这个[commit](https://github.com/Smallpath/Blog/tree/43ec05c6192838d2fe2d96add185ad77d6882db4)。 

你想做什么呢？ TODO里面没完成的你可以挑一个， 或者你想额外做的功能也可以提出来， 没问题的话我可以加进TODO。

**Comment by zhaozhe0831** [comment]
OK!


原始邮件
发件人:Smallpathnotifications@github.com
收件人:Smallpath/BlogBlog@noreply.github.com
抄送:zhaozhe0831420193833@qq.com; Authorauthor@noreply.github.com
发送时间:2016年10月18日(周二) 10:52
主题:Re: [Smallpath/Blog] 带我一个玩呗？ (#1)


谢谢关注， 这两天我在弄ssr， 比较麻烦但估计周五前能弄好， 你要部署的话可以下载之前这个commit。
你想做什么呢？ TODO里面没完成的你可以挑一个， 或者你想额外做的功能也可以提出来， 没问题的话我可以加进TODO。

**Comment by zhaozhe0831** [comment]
你想把这个项目做成什么样呢？类似于 wordpress 那种很全能，扩展性很强，主题扩展的那种吗？

**Comment by Smallpath** [comment]
博客目前在做的是如下三个：
- 提供一个统一的后台管理的前端单页应用， 即client/back， 目前是vue1， 有计划升vue2并用上element， 因为后台管理不必考虑seo， 所以不准备上ssr
- 提供RESTful API， 这部分已经完成了， API在readme最下面
- 最后是提供的一个展示博客前台的应用， 目前是client/front, 已经是vue2并在升ssr

我想做的确实是类似wordpress的， 扩展性强度可以纯粹依靠RESTful， 因为后端是个纯restful服务器，因此只要给后端加数据库表，前端怎么来都可以， 这部分难度相当小

也计划做主题扩展， 不过并不是像hexo那种直接改模版， 而是这个意思： 我提供RESTful API， 你想换主题了就自己拿着这些API去写一个新的博客前台， 至于是用vue还是react还是angular都不会有限制。 这个博客前台甚至可以不是前端页面， 可以是Android/IOS的app， 还可以是Electron这样的桌面端app。

目前RESTful API包括鉴权（OAuth1）都已经做完了， 因此目标其实已经完成了一大半， 接下来我会做的一些TODO如下， 等会儿会更新到readme中：

- 前台单页的vue2.0服务端渲染
- 后台单页升级vue2.0
- 后台单页使用element ui
- 后台单页支持schema的新建/编辑/删除

**Comment by zhaozhe0831** [comment]
那具体的我能做些什么呢？


从 TODO 列表里选就可以吗？


代码结构规范有什么要求？


js css 之类的，按照 stylelint ，eslint 来就行吗？


我看目前是有 eslint 的。


除此之外，其他方面有什么要求吗？


我这面现在是 fork 了一下。

**Comment by Smallpath** [comment]
嗯， 从TODO里选就可以了， 代码规范暂时不用管， 那个是准备每次发新版本时用的， 现在还没用上。 

其他方面的话， 目前暂时不要选前台单页， 那个现在在弄ssr， 目前无法上线， 因此建议你选后台管理单页的一些功能点， 就用vue1.0就可以了。 

如果选服务器端的话， 如果要加新表，和我说一声就ok

**Comment by zhaozhe0831** [comment]
服务端没写过，那我就写后台的功能点了。

**Comment by Smallpath** [comment]
晚上好：
  前台单页的服务端渲染以及对应的部署文档已经完成了， 你可以查看demo尝试SSR效果如何。
  另外，TODO我更新了一些， 你可以看一看
