### ISSUE TITLE
api.js  这段代码不太理解，import api from 'create-api'  ，这个引用在那里

### ISSUE THREAD

**Issue by wwb568109135** [smallpath/blog#18]
import api from 'create-api'

const prefix = `${api.host}/api`

const store = {}

export default store

store.fetch = (model, query) => {
  const target = `${prefix}/${model}`
  return api.axios.get(target, { params: query }).then((response) => {
    const result = response.data
    return result
  })
}

**Comment by smallpath** [comment]
通过webpack [alias](https://github.com/smallpath/blog/blob/master/front/build/webpack.client.config.js#L12)在客户端和服务端分别导入不同的请求库， 客户端请求库为[自造ajax轮子](https://github.com/smallpath/blog/blob/master/front/src/store/client-axios.js), 服务端为伪造成ajax库的[数据库查询逻辑](https://github.com/smallpath/blog/blob/master/front/server/server-axios.js)

相应两篇文章在这:  
- [自造ajax和状态库](https://smallpath.me/post/blog-vuex-wheel)
- [vue2服务端渲染：直连数据库的首屏优化策略](https://smallpath.me/post/vue2-ssr-connect-db)

**Comment by wwb568109135** [comment]
谢谢 之前一直没有找到这个create-api他的引用，现在知道了，谢谢楼主！
