### ISSUE TITLE
关于七牛图片上传

### ISSUE THREAD

**Issue by elva2596** [smallpath/blog#19]
您好，我现在有这样一个需要，因为要做一个很多图片展示类的网站，所以我再后台管理中创建一个基于element ui 上传组件的模板(模板中除了上传组件，还要保存图片的相关信息，即标题，创作的时间，左偏描述，也就是添加其他element ui组件，并绑定相应字段)，我上传到七牛以后，并且填写了其他字段以后，我后台的接口是自己编写的，那么我后台的数据库是否应该保存这些字段(包括从七牛返回的url)。如果是这样的话，我想编辑该作品的时候应该怎么办？因为我后台只保存了图片的url，再次跟新的时候，是重写上传到七牛，然后再次更新数据库中的url吗？有没有什么办法，我更新图片的时候，七牛存储中的图片也更新？

**Comment by smallpath** [comment]
当然可以，七牛图片的上传策略有很多字段可以决定是否覆盖同名图片，编辑完了覆盖掉就ok，另外貌似七牛的node sdk改版了，本项目用的还是以前版本。
