### ISSUE TITLE
在blog列表页点击文字链接进入的时候先显示的是上次加载的内容

### ISSUE THREAD

**Issue by lileltp** [Smallpath/Blog#2]
然后在没有任何提示的状态下,过了一秒多才加载新的内容.

**Comment by Smallpath** [comment]
前台单页还是后台管理单页啊？ 确实存在这个问题，目前后台管理第二版已经加上了loading页，前台火麒麟主题也会加上这个loading组件。

应该在本周内修复

**Comment by lileltp** [comment]
我看的是前台.

**Comment by Smallpath** [comment]
嗯, 一直有这个问题, 因为我这边切换页面速度在100ms以内, 页面一闪而过就刷新好了, 所以之前偷懒没弄前台的loading. 这两天在弄第二版后台管理, 周末腾出手来会解决这个问题.

不过, 你过了一秒多才加载新的内容的话, 应该是服务器(阿里香港B区)问题, 能麻烦你放个ping或者trace smallpath.me的结果么

**Comment by Smallpath** [comment]
后台管理已经换成了element-ui写的v2版, 自带Loading组件
前台增加了github样式的LoadingBar, 今晚在demo那上线
