### ISSUE TITLE
vue的ssr怎么配置webpack

### ISSUE THREAD

**Issue by SoulFlys** [Smallpath/Blog#4]
ssr的理论基本能明白，但是怎么结合webpack进行搭建，求博主告知

**Comment by Smallpath** [comment]
有两点

- 最好在所有页面开发完毕后再上SSR
  - 因为热重载目前貌似只能重载SSR端的server-bundle.js, 边开发页面边弄SSR实在是太痛苦了，改一个地方要重启一次dev-server
- 最好在没上SSR时就有意识地将数据访问接口抽象到组件外部，组件内仅实现一个preFetch接口
  - 这样可以无缝衔接SSR，几乎不用改业务代码

然后接webpack的话，webpack的配置其实直接拿别人配好的用就可以了 。webpack1可以参考[本博客之前的构建配置](https://github.com/Smallpath/Blog/tree/32991fe4d6213b72a54784cdeea913f71acce279/client/front/build)，webpack2可以参考[Evan官方的构建配置](https://github.com/vuejs/vue-hackernews-2.0/tree/master/build)。

详细的配置过程我写过两篇文章，有兴趣的话可以看一看

[Vue2.0服务端渲染: 博客前台升级记录](https://smallpath.me/post/vue-ssr-log)

[Vue2服务端渲染: 踩坑合集](https://smallpath.me/post/vue2-ssr-hardcore)
