### ISSUE TITLE
文章页内容的展示

### ISSUE THREAD

**Issue by SoulFlys** [Smallpath/Blog#6]
我想请教下博主，文章页面显示当前路由对应的文章内容的方法（在什么时候获取数据）

**Comment by Smallpath** [comment]
可以参考一下[这一段](https://smallpath.me/post/vue2-ssr-on-demand-code-splitting-opti#router.beforeeach)

不局限于文章页面，所有页面都可以按这样的数据获取顺序，通过preFetch钩子来控制

**Comment by SoulFlys** [comment]
博主，为啥我在生产环境下F12还能看到请求呢

**Comment by Smallpath** [comment]
你是说哪个请求啊？ 博客刷新的话没有Ajax异步请求和分块加载请求，文章页的请求大多数是disqus评论

**Comment by SoulFlys** [comment]
就是博客刷新的時候會出現類似ajax請求

**Comment by Smallpath** [comment]
纳尼，你截个图看看？

**Comment by SoulFlys** [comment]
![image](https://cloud.githubusercontent.com/assets/12166401/23051891/85821c9c-f507-11e6-9e1d-8f8f4c4074c5.png)

**Comment by Smallpath** [comment]
哦，去除Ajax请求是SSR做的，你需要把它改成SSR形式

**Comment by SoulFlys** [comment]
是ssr啊

**Comment by SoulFlys** [comment]
博主 从首页进入文章页 为什么我的页面不是先把数据渲染完 再渲染页面啊

**Comment by Smallpath** [comment]
官方路由的数据获取是[这样的](https://router.vuejs.org/zh-cn/advanced/data-fetching.html)，分为两种模式，根据SSR的特征，_在导航完成前获取数据_可以充分利用preFetch钩子，因此我觉得更好一些。

详细的描述在[这一节](https://smallpath.me/post/vue2-ssr-on-demand-code-splitting-opti#router.beforeeach)有详细描述

**Comment by SoulFlys** [comment]
博主 你上面说的这种方法 在导航完成前preFetch  但是在server-entry的时候也会preFetch  那么第一次加载的时候会出现两次preFetch 这个怎么解决呢

**Comment by Smallpath** [comment]
导航完成前的preFetch是用router.beforeEach等钩子来做的吧？把他们放到`store.replaceState(window.__INITIAL_STATE__)`语句之后，首屏就不会再次触发preFetch了。原因是使用了vue-router-sync，替换全局状态中的route属性时会触发一次路由钩子
