### ISSUE TITLE
Patch请求和delete请求出问题

### ISSUE THREAD

**Issue by An-l** [Smallpath/Blog#9]
比如编辑更新一片文章，用patch请求访问 http://127.0.0.1:3000/api/post/58c95aa85d311c6e5000e3af 这个地址，出现了下面的错误，但是文章其实已经在数据库已经更新好了。
无论是更新(patch)，删除(delete)文章，分类，标签等，都出现这种问题。
![image](https://cloud.githubusercontent.com/assets/15082628/23957827/4b521e6c-09db-11e7-95ce-5e9e5c83e8a3.png)

后台路由：
![image](https://cloud.githubusercontent.com/assets/15082628/23957930/919d466c-09db-11e7-8dad-c90272005958.png)

后台更新文章方法：
![image](https://cloud.githubusercontent.com/assets/15082628/23981275/3122b654-0a40-11e7-8547-998330947b3f.png)

后台更新文章方法中console.log(result)的提示：
![image](https://cloud.githubusercontent.com/assets/15082628/23981280/3f3035f0-0a40-11e7-84b1-292e05b4e348.png)

在前台使用的是fetch发起请求：
![image](https://cloud.githubusercontent.com/assets/15082628/23981339/af2267f2-0a40-11e7-8e69-b15722258a10.png)

最奇怪的是get请求和post请求都没有问题，只有patch、delete、put请求出现这种问题。

**Comment by Smallpath** [comment]
应该是404返回**Not Found**, 然后你调用res.json()的时候没法把**Not Found**解析成JSON，于是报错说第一个字母N词法错误。

感觉要么是fetch请求格式有错， 要么是后端解析请求格式解析错了，稍后我做一下测试

**Comment by Smallpath** [comment]
我尝试了一下，浏览器环境的fetch和node环境的fetch都没问题啊。
![image](https://cloud.githubusercontent.com/assets/10809900/24004149/842f834e-0aa0-11e7-8baf-cb92788c6c04.png)

你函数中headers里没有authorization字段应该会被服务器拒绝修改的，你是不是自己修改了permission函数？

**Comment by Smallpath** [comment]
你函数中headers里没有authorization字段应该会被服务器拒绝修改的，你是不是自己修改了permission函数？

另外可以贴一下浏览器network页面中patch请求的详情，确保发起的请求没有问题

**Comment by An-l** [comment]
谢谢，看了你的分析之后，我找到问题出现所在了。
因为还没做到验证登录那块，所以我直接把permission函数里面的内容注释掉了，只写了个next()，就出现了以上的问题。
我的解决方法： return netxt();
这样就。。解决了！
是因为koa-router里面的中间件必须return一个值吗？

**Comment by Smallpath** [comment]
next()返回的是promise，估计koa中检查到非promise的返回值时就直接跳到默认的Error Handler中间件了

**Comment by An-l** [comment]
原来是这样，谢谢你啦！
我还想问一下，如果前后台都写好了，准备上线自己的博客，因为服务器端的koa2只是一个简单的REST服务器，那么前后台的网页应该放哪？ 
还是直接修改koa2去render前后台的网页呢？

**Comment by Smallpath** [comment]
看你是前后端分离还是传统的MVC咯，前后端分离的话构建出静态资源用nginx代理即可，传统MVC还需要nginx额外配置端口的信息

**Comment by An-l** [comment]
谢谢！
